# PowerShell script to convert usecases.ts to usecases.js
# Run this with: .\convert-usecases.ps1

Write-Host "Converting usecases.ts to usecases.js..." -ForegroundColor Cyan

# Read the TypeScript file
$tsContent = Get-Content "usecases.ts" -Raw

if ([string]::IsNullOrWhiteSpace($tsContent)) {
    Write-Host "⚠️  usecases.ts is empty!" -ForegroundColor Yellow
    Write-Host "Please make sure you have saved your usecases.ts file with data." -ForegroundColor Yellow
    Write-Host "Creating empty usecases.js as fallback..." -ForegroundColor Yellow
    "window.additionalUsecases = [];" | Out-File -Encoding UTF8 "usecases.js"
    exit
}

# Extract the additionalUsecases array
if ($tsContent -match 'export const additionalUsecases[^=]*=\s*(\[[\s\S]*\]);') {
    $arrayContent = $Matches[1]
    
    # Create the JavaScript version
    $jsContent = @"
// Auto-generated from usecases.ts
// Do not edit this file directly - edit usecases.ts instead

window.additionalUsecases = $arrayContent;
"@
    
    # Write to usecases.js
    $jsContent | Out-File -Encoding UTF8 "usecases.js"
    
    Write-Host "✅ Successfully converted usecases.ts to usecases.js" -ForegroundColor Green
    
    # Try to count use cases
    try {
        $count = ($arrayContent | Select-String -Pattern '"usecase_id"' -AllMatches).Matches.Count
        Write-Host "📊 Found approximately $count use cases" -ForegroundColor Green
    } catch {
        Write-Host "📊 Conversion complete" -ForegroundColor Green
    }
} else {
    Write-Host "⚠️  Could not find 'export const additionalUsecases' in usecases.ts" -ForegroundColor Yellow
    Write-Host "Creating empty usecases.js..." -ForegroundColor Yellow
    "window.additionalUsecases = [];" | Out-File -Encoding UTF8 "usecases.js"
}

Write-Host "`nDone! Refresh your browser to see the changes." -ForegroundColor Cyan
